#!/bin/sh
# Generated by envonce — do not edit. Regenerate: `envonce service sync ollama`
ENVONCE=/opt/homebrew/bin/envonce
out=$("$ENVONCE" env export --service ollama) || exit 1
eval "$out"
exec /opt/homebrew/opt/ollama/bin/ollama serve "$@"
