// Package wrapper generates the shell wrapper script that injects envonce's
// resolved environment variables (via `envonce env export --service`) before
// exec'ing a managed service binary.
package wrapper

import (
	"fmt"
	"strings"
)

// WrapperData holds the inputs used to render a service's wrapper script.
type WrapperData struct {
	EnvonceBin  string
	ServiceName string
	Binary      string
	Args        []string
}

// Generate renders the wrapper shell script for the given service.
func Generate(d WrapperData) string {
	execLine := d.Binary
	if len(d.Args) > 0 {
		execLine += " " + strings.Join(d.Args, " ")
	}
	return fmt.Sprintf(`#!/bin/sh
# Generated by envonce — do not edit. Regenerate: `+"`envonce service sync %s`"+`
ENVONCE=%s
out=$("$ENVONCE" env export --service %s) || exit 1
eval "$out"
exec %s "$@"
`, d.ServiceName, d.EnvonceBin, d.ServiceName, execLine)
}
