// Package wrapper generates the shell wrapper script that injects envonce's
// resolved environment variables (via `envonce env export --service`) before
// exec'ing a managed service binary.
package wrapper

import (
	"fmt"
	"strings"
)

// WrapperData holds the inputs used to render a service's wrapper script.
type WrapperData struct {
	EnvonceBin  string
	ServiceName string
	Binary      string
	Args        []string
}

// Generate renders the wrapper shell script for the given service.
func Generate(d WrapperData) string {
	// Build the exec line by shell-quoting each word (binary included) so that an
	// arg containing spaces — e.g. `-c 'exec ccr serve --port 31171'` — survives as
	// a single word instead of being word-split by /bin/sh. Bare strings with only
	// shell-safe characters stay unquoted for readability, so the common case
	// (e.g. `ollama serve`) is unchanged.
	quoted := make([]string, 0, len(d.Args)+1)
	quoted = append(quoted, shellQuote(d.Binary))
	for _, a := range d.Args {
		quoted = append(quoted, shellQuote(a))
	}
	execLine := strings.Join(quoted, " ")
	return fmt.Sprintf(`#!/bin/sh
# Generated by envonce — do not edit. Regenerate: `+"`envonce service sync %s`"+`
ENVONCE=%s
out=$("$ENVONCE" env export --service %s) || exit 1
eval "$out"
exec %s "$@"
`, d.ServiceName, d.EnvonceBin, d.ServiceName, execLine)
}

// shellQuote renders s as exactly one word on a POSIX sh command line. Strings
// made up solely of shell-safe characters are emitted bare; anything else —
// spaces, quotes, $, backticks, globs, etc. — is wrapped in single quotes, with
// any embedded single quote escaped via the standard `'"'"'` sequence. The empty
// string becomes '' so it is preserved as a distinct argument.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	if isShellSafe(s) {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// isShellSafe reports whether s needs no quoting as a bare POSIX sh word.
func isShellSafe(s string) bool {
	for _, r := range s {
		if !shellSafeRune(r) {
			return false
		}
	}
	return true
}

func shellSafeRune(r rune) bool {
	switch {
	case 'a' <= r && r <= 'z', 'A' <= r && r <= 'Z', '0' <= r && r <= '9':
		return true
	}
	switch r {
	case '.', '_', '-', '/', ':', '@', '%', ',', '+', '=':
		return true
	}
	return false
}
